### ISSUE TITLE
New tab no longer opens Temporary Container with Automatic mode

### ISSUE THREAD

**Issue by MzHub** [stoically/temporary-containers#146]
- Temporary Containers Version: 0.90
- Firefox Version: 60.0.1
- Operating System + Version: Windows 7
- Non-default Options/Preferences in Temporary Containers: Automatic mode on, middle and ctrl clicks always open new container.
- Other installed Add-ons + Version:
  Multi-Account Containers 6.0.0
  uBlock Origin	1.16.6

### Actual behavior
New tab does not open in (or get replaced with) a Temporary Container.

### Expected behavior
New tab opens in (or gets replaced with) a Temporary Container.

### Notes
Just updated Firefox, didn't have this issue before.

**Comment by nameless3** [comment]
I can reproduce using the same version of Firefox and TC, however when I visit a website the tab does turn into a temporary container (except for `about:` pages after quick testing)

Seems like setting `browser.newtabpage.enabled` to `true` fixes it?

**Comment by Perflyst** [comment]
Seems to be a similar/same problem as #150

**Comment by stoically** [comment]
This should be fixed since Firefox version 61. Let me know if it's still a problem.

**Comment by Perflyst** [comment]
The issue is still persistent if about:blank is defined as default start page in about:config

**Comment by stoically** [comment]
@Perflyst I've changed the homepage to about:blank and with just Automatic Mode turned on in TC (everything else is default) pressing Ctrl+T (re)opens a new Temporary Container. This doesn't work for you?

**Comment by Perflyst** [comment]
Seems to be profile releated, just tested in a new one. Indeed is fixed since 61.

**Comment by tya99** [comment]
> The issue is still persistent if about:blank is defined as default start page in about:config

> Seems to be profile releated, just tested in a new one. Indeed is fixed since 61.

It still happens if you use blank pages. I was able to reproduce this in Firefox 65.0

1. Create new profile
2. Installed [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/)
3. Set Automatic Mode
4. Installed a search instance. In this case I chose [searx disroot](https://addons.mozilla.org/en-US/firefox/addon/searx-disroot/)
5. It worked until I changed the "Homepage and new windows" and "New tabs" to "Blank Page", changing it back to "Firefox Home" seemed to fix it. Can I use blank pages if I want?

**Comment by grenzor** [comment]
Can confirm what @tya99 said. On my end about:blank also doesn't open a new container tab.

**Comment by stoically** [comment]
> The issue is still persistent if about:blank is defined as default start page in about:config

> 5\. It worked until I changed the "Homepage and new windows" and "New tabs" to "Blank Page", changing it back to "Firefox Home" seemed to fix it.

Was able to reproduce this for about:blank tabs. The problem is that TC [only checks for about:home and about:newtab](https://github.com/stoically/temporary-containers/blob/229c3dbbcead05bcc2aec5a0e0a9505f83705f31/src/background/tabs.js#L140-L141). However, just adding about:blank to the check doesn't work since the about:blank tab has its URL set `onCreated` but fires an `onUpdated` with about:blank as URL a bit later, resulting in two new tabs - have to figure out a way to circumvent that.

However, POST search engines wont work with the advanced automatic mode setting "Don't reopen" due to the way TC operates in that case.

**Comment by Gitoffthelawn** [comment]
@stoically Just FYI, you mentioned that TC checks for `about:home` and `about:newtab`.  When I type `about:newtab` into the urlbar, it isn't opening in a container, even with automatic mode enabled.

**Comment by stoically** [comment]
Fixed in version 0.92. Let me know if something still doesn't work as expected.

**Comment by stoically** [comment]
FYI, upcoming version 1.4 will no longer reopen "Blank page" (about:blank) tabs due to all sorts of problems with the mechanism to detect that correctly. Would need an explicit API (or tab status) from Firefox. Reopening happens on first navigation instead in that case.
