### ISSUE TITLE
Automatic Mode don't instantly open new tabs not working

### ISSUE THREAD

**Issue by huynhxloi** [stoically/temporary-containers#453]
As of FF 78-79, I've been noticing increasingly frequent occurrences of Temporary Containers automatic mode not opening sites in a container. I have automatic mode set to "Don't instantly open new tabs..." selection. I prefer the Instant option but it loses characters, so I use the alternative. However, it doesn't place my navigated tabs in a container... 

Rough steps to reproduce:
Cmd+N to create new Tab, navigate to a site. 

Expected Behavior:
The site loads in a new container

Actual Behavior:
The site loads in no container

I've seen issue #332, but I already have my New Tabs page set to Firefox Home. 

[My preferences file](https://github.com/stoically/temporary-containers/files/5019742/temporary_containers_preferences_2020-8-3_21.26.5.txt)

**Comment by stoically** [comment]
Thanks for letting me know, I'll try to reproduce. In this specific case a debug log (see wiki for instructions) would be very helpful if you could maybe obtain one.

**Comment by huynhxloi** [comment]
Tell me if you can reproduce using these steps:

1. With the extension set to my preferences
2. Ctrl+T
3. Go to the site: https://www.whatismyip.com/
4. The behavior should be demonstrated

If https://www.whatismyip.com/ doesn't elicit the behavior, the issue seems to occur on slow sites that takes a few seconds to load, so find another site that takes several seconds to load may elicit the behavior.

I think the issue is related to a bug where if a site takes too long to load out of a New Tab, the extension fails to put it into a container. 

Please verify if you can reproduce. Thanks

**Comment by stoically** [comment]
Unfortunately can't reproduce on my end with the given STR, even though the site takes a long time to load.

**Comment by stoically** [comment]
Have you tried with a new profile (about:profiles)?

**Comment by huynhxloi** [comment]
I cant reproduce it now either. There may be other factors affecting this, like RAM usage, number of tabs, etc but I'll keep an eye out next time this happens and hopefully pin down the culprit.

**Comment by huynhxloi** [comment]
It happened again. I'm attaching a screenshot. You can see the tabs without the colored coding are the ones that for some reason the Automatic Mode fail to place into a temp container. 

<img width="1680" alt="Screen Shot 2020-08-05 at 10 30 37 AM" src="https://user-images.githubusercontent.com/12505858/89432648-fb0e1080-d706-11ea-97f0-9ff6a1a05e6c.png">

Here is the debug log. It's quite long. 

[log.log](https://github.com/stoically/temporary-containers/files/5029385/log.log)

**Comment by huynhxloi** [comment]
Shorter one that contains the issue.

[log.log](https://github.com/stoically/temporary-containers/files/5029426/log.log)

**Comment by stoically** [comment]
Interesting, thanks for providing the log. So what happens is that the request to `asiatimes.com` arrives with `cookieStoreId` (container id) set to `firefox-default` (no container). That's odd, since normally tabs inherit the parent tabs container. Do you by chance use the Multi-Account Containers "restrict" feature? If so then you're affected by #439

**Comment by huynhxloi** [comment]
Thanks for the quick response. 

It appears so. I've disabled Multi-Account Containers for now since I realize I don't need both extensions. Let's see if the issue persists, if not then it's likely due to the restrict feature as you said.

**Comment by huynhxloi** [comment]
Caught it in the act again, this time with Multi-Account Container extension disabled.

[log.log](https://github.com/stoically/temporary-containers/files/5030428/log.log)

**Comment by huynhxloi** [comment]
[log.log](https://github.com/stoically/temporary-containers/files/5030436/log.log)

**Comment by stoically** [comment]
Thanks. Ah, I see now what's going on. Your new tabs (`about:newtab`) have a parent set (`openerTab`), which is unusual. Do you by chance use an extension or similar to somehow open new tabs? Or how exactly do you open new tabs?

In either case, it's a bug, since that can and should be caught by automatic mode.

**Comment by stoically** [comment]
Fixed in v1.9

**Comment by huynhxloi** [comment]
Looks like the issue is still around, this time with a Pocket website.

**Comment by huynhxloi** [comment]
Fri, 14 Aug 2020 18:27:20 GMT "[onCreated] tab created" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"complete","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429640985,"audible":false,"mutedInfo":{"muted":false},"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":-1,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:20 GMT "[maybeReopenInTmpContainer] not a home/new tab, we dont handle that" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"complete","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429640985,"audible":false,"mutedInfo":{"muted":false},"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":-1,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"complete","hidden":false,"discarded":false,"incognito":false,"width":0,"height":0,"lastAccessed":1597429640989,"audible":false,"mutedInfo":{"muted":false},"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":-1,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} {"attention":false} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onActivated]" {"tabId":1185,"previousTabId":1182,"windowId":3} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"complete","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641062,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":-1,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} {"isArticle":false} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"complete","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641083,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":-1,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} {"status":"complete","url":"about:blank"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] url changed" {"status":"complete","url":"about:blank"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[maybeReopenInTmpContainer] not a home/new tab, we dont handle that" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"complete","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641083,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":-1,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641100,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":-1,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} {"status":"loading"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[webRequestOnBeforeRequest] incoming request" {"requestId":"178984","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","method":"GET","type":"main_frame","timeStamp":1597429641060,"tabId":1185,"frameId":0,"parentFrameId":-1,"incognito":false,"thirdParty":false,"cookieStoreId":"firefox-default","proxyInfo":null,"ip":null,"frameAncestors":[],"urlClassification":{"firstParty":[],"thirdParty":[]},"requestSize":0,"responseSize":0} background.js:468:25
------------------------------------------ background.js:469:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. bg.min.js:4
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:15
Some cookies are misusing the recommended “sameSite“ attribute 6
Fri, 14 Aug 2020 18:27:21 GMT "[handleRequest] onbeforeRequest requested tab information" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641419,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":-1,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} undefined background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[handleRequest] request url is on the ignoreRequests list" {"requestId":"178984","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","method":"GET","type":"main_frame","timeStamp":1597429641060,"tabId":1185,"frameId":0,"parentFrameId":-1,"incognito":false,"thirdParty":false,"cookieStoreId":"firefox-default","proxyInfo":null,"ip":null,"frameAncestors":[],"urlClassification":{"firstParty":[],"thirdParty":[]},"requestSize":0,"responseSize":0} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641719,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"about:blank","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} {"isArticle":false} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641730,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} {"status":"loading","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] url changed" {"status":"loading","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:21 GMT "[maybeReopenInTmpContainer] not a home/new tab, we dont handle that" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641730,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} background.js:468:25
------------------------------------------ background.js:469:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. bg.min.js:4
Fri, 14 Aug 2020 18:27:21 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429641814,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"Sylvester Stallone Feels Robbed of an Ownership Stake in ‘Rocky’: ‘I Was Furious’"} {"title":"Sylvester Stallone Feels Robbed of an Ownership Stake in ‘Rocky’: ‘I Was Furious’"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:22 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429642105,"audible":false,"mutedInfo":{"muted":false},"isArticle":true,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"Sylvester Stallone Feels Robbed of an Ownership Stake in ‘Rocky’: ‘I Was Furious’"} {"isArticle":true} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:22 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429642177,"audible":false,"mutedInfo":{"muted":false},"isArticle":true,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"Sylvester Stallone Feels Robbed of an Ownership Stake in ‘Rocky’: ‘I Was Furious’"} {"status":"loading","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:22 GMT "[onUpdated] url changed" {"status":"loading","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:22 GMT "[maybeReopenInTmpContainer] not a home/new tab, we dont handle that" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429642177,"audible":false,"mutedInfo":{"muted":false},"isArticle":true,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"Sylvester Stallone Feels Robbed of an Ownership Stake in ‘Rocky’: ‘I Was Furious’"} background.js:468:25
------------------------------------------ background.js:469:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. bg.min.js:4
Fri, 14 Aug 2020 18:27:22 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429642321,"audible":false,"mutedInfo":{"muted":false},"isArticle":true,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"Sylvester Stallone Feels Robbed of an Ownership Stake in ‘Rocky’: ‘I Was Furious’"} {"isArticle":true} background.js:468:25
------------------------------------------ background.js:469:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 webrequest.js:108
Fri, 14 Aug 2020 18:27:22 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"loading","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429642469,"audible":false,"mutedInfo":{"muted":false},"isArticle":true,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"Sylvester Stallone Feels Robbed of an Ownership Stake in ‘Rocky’: ‘I Was Furious’"} {} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:23 GMT "[onUpdated] tab updated" {"id":1185,"index":7,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"complete","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429643281,"audible":false,"mutedInfo":{"muted":false},"isArticle":true,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1182,"cookieStoreId":"firefox-default","url":"https://getpocket.com/explore/item/sylvester-stallone-feels-robbed-of-an-ownership-stake-in-rocky-i-was-furious","title":"Sylvester Stallone Feels Robbed of an Ownership Stake in ‘Rocky’: ‘I Was Furious’"} {"status":"complete"} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:25 GMT "[onUpdated] tab updated" {"id":1182,"index":6,"windowId":3,"highlighted":true,"active":true,"attention":false,"pinned":false,"status":"complete","hidden":false,"discarded":false,"incognito":false,"width":1680,"height":965,"lastAccessed":1597429644956,"audible":false,"mutedInfo":{"muted":false},"isArticle":false,"isInReaderMode":false,"sharingState":{"camera":false,"microphone":false},"successorTabId":1181,"openerTabId":1181,"cookieStoreId":"firefox-default","url":"about:devtools-toolbox?type=extension&id=%7Bc607c8df-14a7-4f28-894f-29e8722976af%7D","title":"Toolbox - Extension / Temporary Containers"} {"attention":false} background.js:468:25
------------------------------------------ background.js:469:25
Fri, 14 Aug 2020 18:27:25 GMT "[onActivated]" {"tabId":1182,"previousTabId":1185,"windowId":3} background.js:468:25
------------------------------------------ background.js:469:25
Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. background.js:15
[Exception... "Failure"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: chrome://extensions/content/child/ext-storage.js :: fireOnChanged :: line 184"  data: no] ext-storage.js:184:21
Uncaught (in promise) Error: An unexpected error occurred undefined

​

**Comment by huynhxloi** [comment]
Never mind, it's working as intended. It looks like getpocket was added to domains that is ignored.
